### PR TITLE
Milestone 3 :- 1) DBMS : DDL commands, 2) OOPs : Array of Objects & Static Elements.

### PR DESCRIPTION
**Pull request by SomendraZ**
OOPS : Array of Objects & Static Elements Video Link :- https://drive.google.com/drive/folders/1gijsK6eoOIAWqlM8b75aJGE__IyFxnNv?usp=sharing
DBMS : DDL commands Video Link :- https://drive.google.com/file/d/1nNDCy_w5dtOoR1ZIWq89zo46i9JUzbo8/view?usp=sharing

### CODE REVIEW

**Comment by Tharun-kailash** [comment]
Hey Somendra, 
I have reviewed the code and video. Could you please book a viva slot for OOP? You can find the calendar link in wiki for the same.
Thanks.

**Comment by PRASANNAPATHI** [comment]
Hey @SomendraZ ,
your explanation is fine.
Execution of created tables is missing (use desc command)
Alter command is missing.(show the change in table after applied)
Same as for Drop (show the change in database after applied).

You can merge it now for DDL (wait until OOP gets approved)
or if you need to score fully, please submit another video with all the things mentioned above.

**Comment by Tharun-kailash** [comment]
For OOP, Merge is approved.

**Comment by PRASANNAPATHI** [comment]
DDL - approved in viva

Please merge it for DDL.

**Pull request merged**
