### PR TITLE
Milestone 1 :- DBMS : Schema and ERD.

### PR DESCRIPTION
**Pull request by SomendraZ**

### CODE REVIEW

**Comment by Kalvium-Program** [comment]
ER Diagram is missing.
Schema Diagram - connections for User and Audit tables are missing.
Can't access the video, drive link is not public.

**Comment by PRASANNAPATHI** [comment]
ER Diagram is missing.
Schema Diagram - connections for User and Audit tables are missing.
Can't access the video, drive link is not public.

**Comment by PRASANNAPATHI** [comment]
Book a slot in my calendar today, for viva session.

https://calendar.kalvium.com/prasannapathi/30min

**Comment by PRASANNAPATHI** [comment]
Why did you merge before getting approval?

**Comment by SomendraZ** [comment]
Sorry, i didn't knew.

**Pull request merged**
