### PR TITLE
Milestone 1 :- DBMS : Schema and ERD and OOPS : Classes & Objects.

### PR DESCRIPTION
**Pull request by SomendraZ**
OOPS : Classes & Objects Video Link :- https://youtu.be/lqlCu8xKtWs

### CODE REVIEW

**Comment by PRASANNAPATHI** [comment]
As discussed in viva, 
Your ERD & Schema is good now,
But try to have proper explanation of what you have implemented.

Please, you merge it for DBMS.

**Review by th3c0d3br34ker — COMMENTED** [review]
thanks @SomendraZ for your submission. 

the self-viva had some crucial points missing
1. the explanation for `Class and Objects`.
2. a demo of the project.

as per out viva discussion, please consider these points on up coming PRs.

**Comment by th3c0d3br34ker** [comment]
Consider making individual PR for each concept.

**Comment by SomendraZ** [comment]
> thanks @SomendraZ for your submission.
> 
> the self-viva had some crucial points missing
> 
> 1. the explanation for `Class and Objects`.
> 2. a demo of the project.
> 
> as per out viva discussion, please consider these points on up coming PRs.

Can i merge now?

**Comment by SomendraZ** [comment]
> Consider making individual PR for each concept.

how to make individual PR for each concept as i have one repo for both as i am making combined project.

**Pull request merged**
